# Generated by Django 3.0 on 2021-02-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
